name: CI Web and API Automation Test using Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:  

jobs:
  cucumberTest:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        
    - name: Grant execute permission for Gradle Wrapper
      run: chmod +x gradlew

    - name: Run all tests
      run: ./gradlew cucumberTest

    - name: Upload Build Artifact
      uses: actions/upload-artifact@v4.3.3
      if: always()
      with:
        name: Cucumber Report
        path: reports

    - name: GitHub Pages action
      uses: peaceiris/actions-gh-pages@v4.0.0
      if: always()
      with:
        personal_token: ${{ secrets.WEB_API_TOKEN }}
        publish_dir: reports
